2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_setup.py:_flush():76] Current SDK version is 0.15.9
2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_setup.py:_flush():76] Configure stats pid to 13544
2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_setup.py:_flush():76] Loading settings from /home2/jainit/.config/wandb/settings
2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_setup.py:_flush():76] Loading settings from /home2/jainit/ANLP-A1/src/wandb/settings
2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_init.py:_log_setup():524] Logging user logs to /home2/jainit/ANLP-A1/src/wandb/run-20230901_213717-56dsrd2d/logs/debug.log
2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_init.py:_log_setup():525] Logging internal logs to /home2/jainit/ANLP-A1/src/wandb/run-20230901_213717-56dsrd2d/logs/debug-internal.log
2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_init.py:init():564] calling init triggers
2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'epochs': 50, 'optimizer': 'Adam', 'batch_size': 64, 'embeddings_dim': 300}
2023-09-01 21:37:17,997 INFO    MainThread:13544 [wandb_init.py:init():588] re-initializing run, found existing run on stack: g3cn15yb
2023-09-01 21:37:17,999 INFO    MainThread:13544 [wandb_run.py:_finish():1894] finishing run jain_it/NNLM/g3cn15yb
2023-09-01 21:37:18,002 ERROR   MainThread:13544 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2023-09-01 21:37:18,002 INFO    MainThread:13544 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-09-01 21:37:18,002 INFO    MainThread:13544 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2023-09-01 21:37:18,002 INFO    MainThread:13544 [wandb_run.py:_atexit_cleanup():2128] got exitcode: 0
2023-09-01 21:37:18,002 INFO    MainThread:13544 [wandb_run.py:_restore():2111] restore
2023-09-01 21:37:18,002 INFO    MainThread:13544 [wandb_run.py:_restore():2117] restore done
2023-09-01 21:37:18,338 INFO    MainThread:13544 [wandb_init.py:init():613] starting backend
2023-09-01 21:37:18,338 INFO    MainThread:13544 [wandb_init.py:init():617] setting up manager
2023-09-01 21:37:18,341 INFO    MainThread:13544 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-09-01 21:37:18,341 INFO    MainThread:13544 [wandb_init.py:init():623] backend started and connected
2023-09-01 21:37:18,346 INFO    MainThread:13544 [wandb_run.py:_label_probe_notebook():1234] probe notebook
2023-09-01 21:37:18,346 INFO    MainThread:13544 [wandb_run.py:_label_probe_notebook():1244] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-09-01 21:37:18,346 INFO    MainThread:13544 [wandb_init.py:init():714] updated telemetry
2023-09-01 21:37:18,445 INFO    MainThread:13544 [wandb_init.py:init():747] communicating run to backend with 60.0 second timeout
